# Generated by Django 5.2.16 on 2026-07-16 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistOutputRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=2048, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=700)),
                ('playlist_type', models.CharField(choices=[('artist', 'Best of Artist'), ('year', 'Best of Year'), ('decade', 'Best of Decade'), ('genre', 'Best of Genre'), ('genre_year', 'Best of Genre and Year'), ('genre_decade', 'Best of Genre and Decade'), ('artist_radio', 'Artist Radio')], db_index=True, max_length=30)),
                ('definition_key', models.CharField(max_length=1000, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('track_count', models.PositiveIntegerField(default=0)),
                ('output_path', models.CharField(blank=True, max_length=4096)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('never_regenerate', models.BooleanField(db_index=True, default=False)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='library.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='library.genre')),
            ],
            options={
                'ordering': ['playlist_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('rationale', models.JSONField(default=dict)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='playlists.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_entries', to='library.track')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('playlist', 'position'), name='unique_playlist_position'), models.UniqueConstraint(fields=('playlist', 'track'), name='unique_playlist_track')],
            },
        ),
    ]
