# Generated by Django 5.2.16 on 2026-07-16 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('requested_manually', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('local', 'Local tags'), ('musicbrainz', 'MusicBrainz'), ('spotify', 'Spotify'), ('lastfm', 'Last.fm'), ('wikipedia', 'Wikipedia'), ('youtube', 'YouTube')], db_index=True, max_length=30)),
                ('entity_kind', models.CharField(db_index=True, max_length=40)),
                ('external_id', models.CharField(max_length=1000)),
                ('canonical_url', models.URLField(blank=True, max_length=2000)),
                ('fetched_at', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'entity_kind', 'external_id'), name='unique_source_record')],
            },
        ),
        migrations.CreateModel(
            name='ExternalTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=1000)),
                ('album_title', models.CharField(blank=True, max_length=700)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('playcount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('popularity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match_confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('match_decision', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tracks', to='library.artist')),
                ('matched_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_matches', to='library.track')),
                ('source_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_track', to='enrichment.sourcerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteworthyEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('spotify_top', 'Spotify top track'), ('lastfm_top', 'Last.fm top track'), ('wikipedia_single', 'Wikipedia single'), ('wikipedia_video', 'Wikipedia music video'), ('youtube_official', 'YouTube official music video'), ('manual', 'Manual')], max_length=40)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('decision', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noteworthy_evidence', to='library.artist')),
                ('external_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='enrichment.externaltrack')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noteworthy_evidence', to='library.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('external_track', 'evidence_type'), name='unique_external_track_evidence')],
            },
        ),
        migrations.CreateModel(
            name='RelatedArtistEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_artist_name', models.CharField(max_length=500)),
                ('relationship_type', models.CharField(choices=[('similar', 'Similar artist'), ('member_of', 'Shares members'), ('touring', 'Toured together'), ('collaborator', 'Collaborator')], max_length=30)),
                ('source', models.CharField(choices=[('local', 'Local tags'), ('musicbrainz', 'MusicBrainz'), ('spotify', 'Spotify'), ('lastfm', 'Last.fm'), ('wikipedia', 'Wikipedia'), ('youtube', 'YouTube')], max_length=30)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('decision', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='library.artist')),
                ('related_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='library.artist')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrichment.sourcerecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('artist', 'related_artist_name', 'relationship_type', 'source'), name='unique_related_artist_evidence')],
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('local', 'Local tags'), ('musicbrainz', 'MusicBrainz'), ('spotify', 'Spotify'), ('lastfm', 'Last.fm'), ('wikipedia', 'Wikipedia'), ('youtube', 'YouTube')], max_length=30)),
                ('entity_kind', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=1000)),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('decision', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='library.album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='library.artist')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='library.track')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrichment.sourcerecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'entity_kind', 'external_id'), name='unique_external_identifier')],
            },
        ),
        migrations.CreateModel(
            name='AlbumGenreEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('local', 'Local tags'), ('musicbrainz', 'MusicBrainz'), ('spotify', 'Spotify'), ('lastfm', 'Last.fm'), ('wikipedia', 'Wikipedia'), ('youtube', 'YouTube')], max_length=30)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('decision', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_evidence', to='library.album')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_evidence', to='library.genre')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrichment.sourcerecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('album', 'genre', 'source'), name='unique_album_genre_evidence')],
            },
        ),
    ]
