# Generated by Django 5.2.16 on 2026-07-16 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSourceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('local', 'Local tags'), ('musicbrainz', 'MusicBrainz'), ('spotify', 'Spotify'), ('lastfm', 'Last.fm'), ('wikipedia', 'Wikipedia'), ('youtube', 'YouTube')], max_length=30)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_statuses', to='library.artist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('artist', 'source'), name='unique_artist_source_status')],
            },
        ),
    ]
