# Generated by Django 5.2.16 on 2026-07-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0003_artistrecommendation'),
        ('library', '0004_servicesettings_track_match_auto_accept_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('local', 'Local tags'), ('musicbrainz', 'MusicBrainz'), ('spotify', 'Spotify'), ('lastfm', 'Last.fm'), ('wikipedia', 'Wikipedia'), ('youtube', 'YouTube')], max_length=30)),
                ('external_id', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=700)),
                ('normalized_title', models.CharField(db_index=True, max_length=700)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('release_type', models.CharField(blank=True, max_length=120)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_albums', to='library.artist')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrichment.sourcerecord')),
            ],
            options={
                'ordering': ['artist__name', 'year', 'title'],
                'constraints': [models.UniqueConstraint(fields=('artist', 'source', 'external_id'), name='unique_missing_album')],
            },
        ),
    ]
